# Generated by Django 2.2.3 on 2019-09-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20190713_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'Bulletin', 'verbose_name_plural': 'Bulletins'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Rubric', 'verbose_name_plural': 'Rubrics'},
        ),
    ]
